[general]
import             = ["~/.config/alacritty/tokyonight.toml"]
live_config_reload = false

[window]
dimensions      = { columns = 100, lines = 100 }
dynamic_padding = true
opacity         = 0.96
blur            = true

[font]
size   = 11.5
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Medium" }

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"
