#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name  = "AminurAlam"
email = "64137875+AminurAlam@users.noreply.github.com"

[git]
colocate = false

[ui]
editor          = "nvim"
default-command = "log"

[templates]
log = "pretty"

[template-aliases]
# https://github.com/jj-vcs/jj/blob/main/cli/src/config/templates.toml
description_placeholder = 'label("description placeholder", "\"\"")'
pretty                  = "pretty(self)"
'pretty(commit)'        = '''

if(commit.root(),
  format_root_commit(commit),
  label(
    separate(" ",
      if(commit.current_working_copy(), "working_copy"),
      if(commit.immutable(), "immutable", "mutable"),
      if(commit.conflict(), "conflicted"),
    ),
    concat(
      separate(" ",
        if(false, commit.change_id().shortest()),
        if(true, format_short_change_id_with_change_offset(commit)),
        if(false, format_short_commit_id(commit.commit_id())),
        if(!commit.mine(), commit.author().name()),
        commit_timestamp(commit).ago(),
        commit.bookmarks(),
        commit.tags(),
        commit.working_copies(),
        if(commit.contained_in('first_parent(@)'), label("git_head", "HEAD")),
        if(commit.conflict(), label("conflict", "conflict")),
        if(config("ui.show-cryptographic-signatures").as_boolean(),
          format_short_cryptographic_signature(commit.signature())),
        if(commit.empty(), label("empty", "(empty)")),
        if(commit.description(),
          commit.description().first_line(),
          label(if(commit.empty(), "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''
