[formatting]
align_comments        = true
align_entries         = true
allowed_blank_lines   = 2
array_auto_collapse   = true
array_auto_expand     = true
array_trailing_comma  = true
column_width          = 120
compact_arrays        = true
compact_entries       = false
compact_inline_tables = false
crlf                  = false
indent_entries        = false
indent_string         = "  "
indent_tables         = false
inline_table_expand   = false
reorder_arrays        = false
reorder_keys          = false
trailing_newline      = true
