# $username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$docker_context$package$bun$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$golang$haskell$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$memory_usage$aws$gcloud$openstack$azure$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$time$status$container$shell$character
"$schema" = 'https://starship.rs/config-schema.json'
format = '$directory$git_branch$hostname$sudo$custom$character'
right_format = '$status$cmd_duration$jobs'
continuation_prompt = '[âˆ™](bright-black) '
scan_timeout = 50
command_timeout = 200
add_newline = true

[character]
format = '$symbol '
success_symbol = '[â¯](bold)'
error_symbol = '[â¯](bold red)'
vimcmd_symbol = '[î˜«â¯](bold green)'
vimcmd_visual_symbol = '[î˜«â¯](bold purple)'
vimcmd_replace_symbol = '[î˜«â¯](bold purple)'
vimcmd_replace_one_symbol = '[î˜«â¯](bold purple)'
disabled = false

[cmd_duration]
min_time = 20
format = '\[[$duration](cyan)\]'
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 1
use_logical_path = true
format = ' [$path](bold green)[$read_only](red) '
disabled = false
read_only = ' ï ½'
truncation_symbol = 'â€¦/'
home_symbol = '~'
use_os_path_sep = true

# [directory.substitutions]

[git_branch]
format = '[$symbol$branch](bold purple) '
symbol = 'îœ¥ '
truncation_length = 922
truncation_symbol = 'â€¦'
only_attached = false
always_show_remote = false
ignore_branches = []
disabled = false

[hostname]
ssh_only = true
trim_at = '.'
format = 'ðŸŒ '
disabled = false

[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 2
format = '\[[$symbol$number](blue)\]'
symbol = 'âœ¦'
disabled = false

[localip]
ssh_only = true
format = '[$localipv4](yellow bold) '
disabled = true

[status]
format = '\[[$symbol$status](red)\]'
symbol = 'âœ˜'
success_symbol = ''
not_executable_symbol = 'ï™™'
not_found_symbol = 'ï€‚'
sigint_symbol = 'ðŸ§±'
signal_symbol = 'î€Š'
map_symbol = false
recognize_signal_code = true
pipestatus = true
pipestatus_separator = '|'
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int](red)'
disabled = false

[sudo]
format = '[$symbol sudo](bold blue) '
symbol = '#'
allow_windows = false
disabled = true

[time]
format = 'at [$time](bold yellow) '
use_12hr = false
disabled = true
utc_time_offset = 'local'
time_range = '-'

[username]
format = '[$user]($style) in '
style_root = 'red bold'
style_user = 'yellow bold'
show_always = false
disabled = false

# [custom.newline]
# format = "\n  "
# when = '[ (string length (prompt_pwd)) -gt 18 ]'
# shell = [ "fish", "--no-config", "--private" ]
