#:schema https://yazi-rs.github.io/schemas/theme.json
#:schema /home/fisher/repos/yazi-schemas/schemas/theme.json

[flavor]

[mgr]
cwd = { fg = "blue" }
# Find
find_keyword = { fg = "#ff9e64", bold = true }
find_position = { bg = "#2e3c64", bold = true }
# Symlink
symlink_target = { italic = true }
# Marker
marker_copied = { fg = "green", bg = "green" }
marker_cut = { fg = "yellow", bg = "yellow" }
marker_marked = { fg = "lightblue", bg = "lightblue" }
marker_selected = { fg = "blue", bg = "blue" }
# Count
count_copied = { fg = "black", bg = "green" }
count_cut = { fg = "black", bg = "yellow" }
count_selected = { fg = "black", bg = "blue" }
# Border
border_symbol = " "            # "│"
border_style = { fg = "gray" }
# Highlighting
syntect_theme = "~/repos/dotfiles/yazi/tmtheme.xml"

[tabs]
active = { bg = "red", fg = "black" }
inactive = { fg = "red", bg = "darkgray" }
sep_inner = { open = " ", close = " " }
sep_outer = { open = " ", close = " " }

[spot]
# title = { fg = "green" }

[indicator]
current = { bg = "#2e3c64", bold = true }
# current = { reversed = true }
preview = { bold = true }

[status]
# TODO: change fg to black
progress_label = { bold = true }
progress_normal = { fg = "black", bg = "green" }
progress_error = { fg = "black", bg = "red" }

[input]
# border   = { fg = "#24283b" }
selected = { bg = "#2e3c64" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "cyan" },
  # Media
  { mime = "video/*", fg = "magenta" },
  { mime = "audio/*", fg = "cyan" },
  # Archives
  { mime = "application/zip", fg = "#f7768e" },
  { mime = "application/x-tar", fg = "#f7768e" },
  { mime = "application/x-bzip*", fg = "#f7768e" },
  { mime = "application/x-bzip2", fg = "#f7768e" },
  { mime = "application/x-7z-compressed", fg = "#f7768e" },
  { mime = "application/x-rar", fg = "#f7768e" },
  { mime = "application/x-xz", fg = "#f7768e" },
  { mime = "application/zstd", fg = "#f7768e" },
  # Documents
  { mime = "application/doc", fg = "#db4b4b" },
  { mime = "application/epub+zip", fg = "#db4b4b" },
  { mime = "application/pdf", fg = "#db4b4b" },
  { mime = "application/rtf", fg = "#db4b4b" },
  { mime = "application/vnd.*", fg = "#db4b4b" },
  # Fallback
  { url = "*", fg = "#c6d0f5" },
  { url = "*/", fg = "blue" },
]

[icon]
dirs = [
  { name = ".config", text = "" },
  { name = "dotfiles", text = "" },
  { name = ".git", text = "" },
  { name = ".github", text = "" },
  { name = ".npm", text = "" },
  { name = "Desktop", text = "" },
  { name = "doc", text = "" },
  { name = "dl", text = "" },
  { name = "Library", text = "" },
  { name = "Movies", text = "" },
  { name = "mu", text = "" },
  { name = "pic", text = "" },
  { name = "Public", text = "" },
  { name = "vid", text = "" },
  { name = "repos", text = "󰳐" },
]
