#:schema https://yazi-rs.github.io/schemas/theme.json
#:schema /home/fisher/repos/yazi-schemas/schemas/theme.json

[flavor]
# use = "tokyo-night"
dark = "tokyo-night"


[mgr]
count_copied    = { fg = "black", bg = "green" }
count_cut       = { fg = "black", bg = "red" }
count_selected  = { fg = "black", bg = "yellow" }
hovered         = { bg = "#2e3c64", bold = true }
preview_hovered = { bold = true }

find_keyword  = { fg = "#ff9e64", bold = true }
find_position = { fg = "white", bg = "#2e3c64", bold = true }


[tabs]
active   = { bg = "red", fg = "black" }
inactive = { fg = "red", bg = "lightblack" }

sep_inner = { open = " ", close = " " }
sep_outer = { open = " ", close = " " }

[spot]
title = { fg = 'green' }
