#:schema https://yazi-rs.github.io/schemas/theme.json
#:schema /home/fisher/repos/yazi-schemas/schemas/theme.json

[flavor]

[mgr]
cwd = { fg = "blue" }
# Find
find_keyword = { fg = "#ff9e64", bold = true }
find_position = { bg = "#2e3c64", bold = true }
# Symlink
symlink_target = { italic = true }
# Marker
marker_copied = { fg = "green", bg = "green" }
marker_cut = { fg = "yellow", bg = "yellow" }
marker_marked = { fg = "lightblue", bg = "lightblue" }
marker_selected = { fg = "blue", bg = "blue" }
# Count
count_copied = { fg = "black", bg = "green" }
count_cut = { fg = "black", bg = "yellow" }
count_selected = { fg = "black", bg = "blue" }
# Border
border_symbol = "│"
border_style = { fg = "darkgray" }
# Highlighting
syntect_theme = "~/repos/dotfiles/yazi/tmtheme.xml"

[tabs]
active = { bg = "red", fg = "black" }
inactive = { fg = "red", bg = "darkgray" }
sep_inner = { open = " ", close = " " }
sep_outer = { open = " ", close = " " }

[spot]
# title = { fg = "green" }

[indicator]
current = { bg = "#2e3c64", bold = true }
# current = { reversed = true }
preview = { bold = true }

[status]
progress_label = { bold = true }
progress_normal = { fg = "black", bg = "green" }
progress_error = { fg = "black", bg = "red" }

[input]
# border   = { fg = "#24283b" }
selected = { bg = "#2e3c64" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "cyan" },
  # Media
  { mime = "video/*", fg = "magenta" },
  { mime = "audio/*", fg = "cyan" },
  # Archives
  { mime = "application/zip", fg = "#f7768e" },
  { mime = "application/x-tar", fg = "#f7768e" },
  { mime = "application/x-bzip*", fg = "#f7768e" },
  { mime = "application/x-bzip2", fg = "#f7768e" },
  { mime = "application/x-7z-compressed", fg = "#f7768e" },
  { mime = "application/x-rar", fg = "#f7768e" },
  { mime = "application/x-xz", fg = "#f7768e" },
  { mime = "application/zstd", fg = "#f7768e" },
  # Documents
  { mime = "application/doc", fg = "#db4b4b" },
  { mime = "application/epub+zip", fg = "#db4b4b" },
  { mime = "application/pdf", fg = "#db4b4b" },
  { mime = "application/rtf", fg = "#db4b4b" },
  { mime = "application/vnd.*", fg = "#db4b4b" },
  # Fallback
  { url = "*", fg = "#c6d0f5" },
  { url = "*/", fg = "blue" },
]

[icon]
conds = [{ if = "dir", text = "", fg = "blue" }]

dirs = [
  { name = ".config", text = "" },
  { name = "dotfiles", text = "" },
  { name = ".git", text = "" },
  { name = ".github", text = "" },
  { name = ".npm", text = "" },
  { name = "Desktop", text = "" },
  { name = "doc", text = "" },
  { name = "dl", text = "" },
  { name = "Library", text = "" },
  { name = "Movies", text = "" },
  { name = "mu", text = "" },
  { name = "pic", text = "" },
  { name = "Public", text = "" },
  { name = "vid", text = "" },
  { name = "repos", text = "󰳐" },
]

exts = [
  { name = "cbz", text = "󰂺", fg = "#ffffff" },
  { name = "3gp", text = "", fg = "#fd971f" },
  { name = "3mf", text = "󰆧", fg = "#888888" },
  { name = "7z", text = "", fg = "#eca517" },
  { name = "a", text = "", fg = "#dcddd6" },
  { name = "aac", text = "", fg = "#00afff" },
  { name = "aif", text = "", fg = "#00afff" },
  { name = "aiff", text = "", fg = "#00afff" },
  { name = "ape", text = "", fg = "#00afff" },
  { name = "apk", text = "", fg = "#34a853" },
  { name = "app", text = "", fg = "#9f0500" },
  { name = "asc", text = "󰦝", fg = "#576d7f" },
  { name = "ass", text = "󰨖", fg = "#ffb713" },
  { name = "astro", text = "", fg = "#e23f67" },
  { name = "avif", text = "", fg = "#a074c4" },
  { name = "awk", text = "", fg = "#4d5a5e" },
  { name = "bak", text = "󰁯", fg = "#6d8086" },
  { name = "bkup", text = "󰁯", fg = "#6d8086" },
  { name = "bash", text = "", fg = "#89e051" },
  { name = "bat", text = "", fg = "#c1f12e" },
  { name = "bazel", text = "", fg = "#89e051" },
  { name = "bib", text = "󱉟", fg = "#cbcb41" },
  { name = "bin", text = "", fg = "#9f0500" },
  { name = "blade.php", text = "", fg = "#f05340" },
  { name = "blend", text = "󰂫", fg = "#ea7600" },
  { name = "bmp", text = "", fg = "#a074c4" },
  { name = "bz", text = "", fg = "#eca517" },
  { name = "bz2", text = "", fg = "#eca517" },
  { name = "bz3", text = "", fg = "#eca517" },
  { name = "bzl", text = "", fg = "#89e051" },
  { name = "c", text = "", fg = "#599eff" },
  { name = "c++", text = "", fg = "#f34b7d" },
  { name = "cache", text = "", fg = "#ffffff" },
  { name = "cc", text = "", fg = "#f34b7d" },
  { name = "ccm", text = "", fg = "#f34b7d" },
  { name = "cfg", text = "", fg = "#6d8086" },
  { name = "cfm", text = "", fg = "#01a4ba" },
  { name = "cjs", text = "", fg = "#cbcb41" },
  { name = "clj", text = "", fg = "#8dc149" },
  { name = "cljc", text = "", fg = "#8dc149" },
  { name = "cljd", text = "", fg = "#519aba" },
  { name = "cljs", text = "", fg = "#519aba" },
  { name = "cmake", text = "", fg = "#dce3eb" },
  { name = "conda", text = "", fg = "#43b02a" },
  { name = "conf", text = "", fg = "#6d8086" },
  { name = "cp", text = "", fg = "#519aba" },
  { name = "cpp", text = "", fg = "#519aba" },
  { name = "cppm", text = "", fg = "#519aba" },
  { name = "cr", text = "", fg = "#c8c8c8" },
  { name = "cs", text = "󰌛", fg = "#596706" },
  { name = "csh", text = "", fg = "#4d5a5e" },
  { name = "cson", text = "", fg = "#cbcb41" },
  { name = "css", text = "", fg = "#663399" },
  { name = "csv", text = "", fg = "#89e051" },
  { name = "cue", text = "󰲹", fg = "#ed95ae" },
  { name = "cxx", text = "", fg = "#519aba" },
  { name = "cxxm", text = "", fg = "#519aba" },
  { name = "d.ts", text = "", fg = "#d59855" },
  { name = "dart", text = "", fg = "#03589c" },
  { name = "db", text = "", fg = "#dad8d8" },
  { name = "dconf", text = "", fg = "#ffffff" },
  { name = "desktop", text = "", fg = "#563d7c" },
  { name = "diff", text = "", fg = "#41535b" },
  { name = "dll", text = "", fg = "#4d2c0b" },
  { name = "doc", text = "󰈬", fg = "#185abd" },
  { name = "Dockerfile", text = "󰡨", fg = "#458ee6" },
  { name = "dockerignore", text = "󰡨", fg = "#458ee6" },
  { name = "docx", text = "󰈬", fg = "#185abd" },
  { name = "ebook", text = "", fg = "#eab16d" },
  { name = "ebuild", text = "", fg = "#4c416e" },
  { name = "edn", text = "", fg = "#519aba" },
  { name = "eex", text = "", fg = "#a074c4" },
  { name = "el", text = "", fg = "#8172be" },
  { name = "elc", text = "", fg = "#8172be" },
  { name = "elf", text = "", fg = "#9f0500" },
  { name = "elm", text = "", fg = "#519aba" },
  { name = "eln", text = "", fg = "#8172be" },
  { name = "env", text = "", fg = "#faf743" },
  { name = "epub", text = "", fg = "#eab16d" },
  { name = "erl", text = "", fg = "#b83998" },
  { name = "exe", text = "", fg = "#9f0500" },
  { name = "exs", text = "", fg = "#a074c4" },
  { name = "f#", text = "", fg = "#519aba" },
  { name = "f3d", text = "󰻫", fg = "#839463" },
  { name = "fish", text = "", fg = "#4d5a5e" },
  { name = "flac", text = "", fg = "#0075aa" },
  { name = "fnl", text = "", fg = "#fff3d7" },
  { name = "gd", text = "", fg = "#6d8086" },
  { name = "gif", text = "", fg = "#a074c4" },
  { name = "git", text = "", fg = "#f14c28" },
  { name = "gleam", text = "", fg = "#ffaff3" },
  { name = "glsl", text = "", fg = "#5586a6" },
  { name = "go", text = "", fg = "#00add8" },
  { name = "godot", text = "", fg = "#6d8086" },
  { name = "gradle", text = "", fg = "#005f87" },
  { name = "gz", text = "", fg = "#eca517" },
  { name = "h", text = "", fg = "#a074c4" },
  { name = "hbs", text = "", fg = "#f0772b" },
  { name = "hh", text = "", fg = "#a074c4" },
  { name = "hpp", text = "", fg = "#a074c4" },
  { name = "hs", text = "", fg = "#a074c4" },
  { name = "htm", text = "", fg = "#e34c26" },
  { name = "html", text = "", fg = "#e44d26" },
  { name = "http", text = "", fg = "#008ec7" },
  { name = "hx", text = "", fg = "#ea8220" },
  { name = "hxx", text = "", fg = "#a074c4" },
  { name = "ical", text = "", fg = "#2b2e83" },
  { name = "icalendar", text = "", fg = "#2b2e83" },
  { name = "ico", text = "", fg = "#cbcb41" },
  { name = "ics", text = "", fg = "#2b2e83" },
  { name = "ifb", text = "", fg = "#2b2e83" },
  { name = "image", text = "", fg = "#d0bec8" },
  { name = "img", text = "", fg = "#d0bec8" },
  { name = "info", text = "", fg = "#ffffcd" },
  { name = "ini", text = "", fg = "#6d8086" },
  { name = "ino", text = "", fg = "#56b6c2" },
  { name = "ipynb", text = "", fg = "#f57d01" },
  { name = "iso", text = "", fg = "#d0bec8" },
  { name = "ixx", text = "", fg = "#519aba" },
  { name = "jar", text = "", fg = "#ffaf67" },
  { name = "java", text = "", fg = "#cc3e44" },
  { name = "jl", text = "", fg = "#a270ba" },
  { name = "jpeg", text = "", fg = "#a074c4" },
  { name = "jpg", text = "", fg = "#a074c4" },
  { name = "js", text = "", fg = "#cbcb41" },
  { name = "json", text = "", fg = "#cbcb41" },
  { name = "json5", text = "", fg = "#cbcb41" },
  { name = "jsonc", text = "", fg = "#cbcb41" },
  { name = "jsx", text = "", fg = "#20c2e3" },
  { name = "jxl", text = "", fg = "#a074c4" },
  { name = "kbx", text = "󰯄", fg = "#737672" },
  { name = "kdb", text = "", fg = "#529b34" },
  { name = "kdbx", text = "", fg = "#529b34" },
  { name = "kdenlive", text = "", fg = "#83b8f2" },
  { name = "kdenlivetitle", text = "", fg = "#83b8f2" },
  { name = "ko", text = "", fg = "#dcddd6" },
  { name = "kpp", text = "", fg = "#f245fb" },
  { name = "kra", text = "", fg = "#f245fb" },
  { name = "krz", text = "", fg = "#f245fb" },
  { name = "ksh", text = "", fg = "#4d5a5e" },
  { name = "kt", text = "", fg = "#7f52ff" },
  { name = "kts", text = "", fg = "#7f52ff" },
  { name = "leex", text = "", fg = "#a074c4" },
  { name = "less", text = "", fg = "#563d7c" },
  { name = "lhs", text = "", fg = "#a074c4" },
  { name = "lib", text = "", fg = "#4d2c0b" },
  { name = "license", text = "", fg = "#cbcb41" },
  { name = "lock", text = "", fg = "#bbbbbb" },
  { name = "log", text = "󰌱", fg = "#dddddd" },
  { name = "lrc", text = "󰨖", fg = "#ffb713" },
  { name = "lua", text = "", fg = "#51a0cf" },
  { name = "luac", text = "", fg = "#51a0cf" },
  { name = "luau", text = "", fg = "#00a2ff" },
  { name = "m3u", text = "󰲹", fg = "#ed95ae" },
  { name = "m3u8", text = "󰲹", fg = "#ed95ae" },
  { name = "m4a", text = "", fg = "#00afff" },
  { name = "m4v", text = "", fg = "#fd971f" },
  { name = "magnet", text = "", fg = "#a51b16" },
  { name = "makefile", text = "", fg = "#6d8086" },
  { name = "markdown", text = "", fg = "#dddddd" },
  { name = "md", text = "", fg = "#dddddd" },
  { name = "md5", text = "󰕥", fg = "#8c86af" },
  { name = "mdx", text = "", fg = "#519aba" },
  { name = "mk", text = "", fg = "#6d8086" },
  { name = "mkv", text = "", fg = "#fd971f" },
  { name = "ml", text = "", fg = "#e37933" },
  { name = "mli", text = "", fg = "#e37933" },
  { name = "mo", text = "", fg = "#9772fb" },
  { name = "mobi", text = "", fg = "#eab16d" },
  { name = "mov", text = "", fg = "#fd971f" },
  { name = "mp3", text = "", fg = "#00afff" },
  { name = "mp4", text = "", fg = "#fd971f" },
  { name = "mpp", text = "", fg = "#519aba" },
  { name = "mustache", text = "", fg = "#e37933" },
  { name = "nfo", text = "", fg = "#ffffcd" },
  { name = "nim", text = "", fg = "#f3d400" },
  { name = "nix", text = "", fg = "#7ebae4" },
  { name = "nu", text = "", fg = "#3aa675" },
  { name = "o", text = "", fg = "#9f0500" },
  { name = "obj", text = "󰆧", fg = "#888888" },
  { name = "odf", text = "", fg = "#ff5a96" },
  { name = "odg", text = "", fg = "#fffb57" },
  { name = "odin", text = "󰟢", fg = "#3882d2" },
  { name = "odp", text = "", fg = "#fe9c45" },
  { name = "ods", text = "", fg = "#78fc4e" },
  { name = "odt", text = "", fg = "#2dcbfd" },
  { name = "oga", text = "", fg = "#0075aa" },
  { name = "ogg", text = "", fg = "#0075aa" },
  { name = "ogv", text = "", fg = "#fd971f" },
  { name = "ogx", text = "", fg = "#fd971f" },
  { name = "opus", text = "", fg = "#0075aa" },
  { name = "org", text = "", fg = "#77aa99" },
  { name = "otf", text = "", fg = "#ececec" },
  { name = "out", text = "", fg = "#9f0500" },
  { name = "part", text = "", fg = "#44cda8" },
  { name = "patch", text = "", fg = "#41535b" },
  { name = "pck", text = "", fg = "#6d8086" },
  { name = "pcm", text = "", fg = "#0075aa" },
  { name = "pdf", text = "", fg = "#b30b00" },
  { name = "php", text = "", fg = "#a074c4" },
  { name = "pls", text = "󰲹", fg = "#ed95ae" },
  { name = "png", text = "", fg = "#a074c4" },
  { name = "po", text = "", fg = "#2596be" },
  { name = "pot", text = "", fg = "#2596be" },
  { name = "ppt", text = "󰈧", fg = "#cb4a32" },
  { name = "pptx", text = "󰈧", fg = "#cb4a32" },
  { name = "prisma", text = "", fg = "#5a67d8" },
  { name = "pro", text = "", fg = "#e4b854" },
  { name = "ps1", text = "󰨊", fg = "#4273ca" },
  { name = "psd1", text = "󰨊", fg = "#6975c4" },
  { name = "psm1", text = "󰨊", fg = "#6975c4" },
  { name = "pub", text = "󰷖", fg = "#e3c58e" },
  { name = "pxd", text = "", fg = "#5aa7e4" },
  { name = "pxi", text = "", fg = "#5aa7e4" },
  { name = "py", text = "", fg = "#ffbc03" },
  { name = "pyc", text = "", fg = "#ffe291" },
  { name = "pyd", text = "", fg = "#ffe291" },
  { name = "pyi", text = "", fg = "#ffbc03" },
  { name = "pyo", text = "", fg = "#ffe291" },
  { name = "pyw", text = "", fg = "#5aa7e4" },
  { name = "pyx", text = "", fg = "#5aa7e4" },
  { name = "qml", text = "", fg = "#40cd52" },
  { name = "qrc", text = "", fg = "#40cd52" },
  { name = "qss", text = "", fg = "#40cd52" },
  { name = "R", text = "󰟔", fg = "#2266ba" },
  { name = "r", text = "󰟔", fg = "#2266ba" },
  { name = "rar", text = "", fg = "#eca517" },
  { name = "rb", text = "", fg = "#701516" },
  { name = "rlib", text = "", fg = "#dea584" },
  { name = "rmd", text = "", fg = "#519aba" },
  { name = "rs", text = "", fg = "#dea584" },
  { name = "rss", text = "", fg = "#fb9d3b" },
  { name = "sass", text = "", fg = "#f55385" },
  { name = "sbt", text = "", fg = "#cc3e44" },
  { name = "sc", text = "", fg = "#cc3e44" },
  { name = "scala", text = "", fg = "#cc3e44" },
  { name = "scm", text = "󰘧", fg = "#eeeeee" },
  { name = "scss", text = "", fg = "#f55385" },
  { name = "sh", text = "", fg = "#4d5a5e" },
  { name = "sha1", text = "󰕥", fg = "#8c86af" },
  { name = "sha224", text = "󰕥", fg = "#8c86af" },
  { name = "sha256", text = "󰕥", fg = "#8c86af" },
  { name = "sha384", text = "󰕥", fg = "#8c86af" },
  { name = "sha512", text = "󰕥", fg = "#8c86af" },
  { name = "sig", text = "󰘧", fg = "#e37933" },
  { name = "signature", text = "󰘧", fg = "#e37933" },
  { name = "slim", text = "", fg = "#e34c26" },
  { name = "sml", text = "󰘧", fg = "#e37933" },
  { name = "so", text = "", fg = "#dcddd6" },
  { name = "spec.js", text = "", fg = "#cbcb41" },
  { name = "spec.jsx", text = "", fg = "#20c2e3" },
  { name = "spec.ts", text = "", fg = "#519aba" },
  { name = "spec.tsx", text = "", fg = "#1354bf" },
  { name = "spx", text = "", fg = "#0075aa" },
  { name = "sql", text = "", fg = "#dad8d8" },
  { name = "sqlite", text = "", fg = "#dad8d8" },
  { name = "sqlite3", text = "", fg = "#dad8d8" },
  { name = "srt", text = "󰨖", fg = "#ffb713" },
  { name = "ssa", text = "󰨖", fg = "#ffb713" },
  { name = "strings", text = "", fg = "#2596be" },
  { name = "sub", text = "󰨖", fg = "#ffb713" },
  { name = "svelte", text = "", fg = "#ff3e00" },
  { name = "svg", text = "󰜡", fg = "#ffb13b" },
  { name = "svgz", text = "󰜡", fg = "#ffb13b" },
  { name = "terminal", text = "", fg = "#31b53e" },
  { name = "test.js", text = "", fg = "#cbcb41" },
  { name = "test.jsx", text = "", fg = "#20c2e3" },
  { name = "test.ts", text = "", fg = "#519aba" },
  { name = "test.tsx", text = "", fg = "#1354bf" },
  { name = "tex", text = "", fg = "#3d6117" },
  { name = "tf", text = "", fg = "#5f43e9" },
  { name = "tfvars", text = "", fg = "#5f43e9" },
  { name = "tgz", text = "", fg = "#eca517" },
  { name = "tmpl", text = "", fg = "#dbbd30" },
  { name = "tmux", text = "", fg = "#14ba19" },
  { name = "toml", text = "", fg = "#9c4221" },
  { name = "torrent", text = "", fg = "#44cda8" },
  { name = "tres", text = "", fg = "#6d8086" },
  { name = "ts", text = "", fg = "#519aba" },
  { name = "tscn", text = "", fg = "#6d8086" },
  { name = "tsconfig", text = "", fg = "#ff8700" },
  { name = "tsx", text = "", fg = "#1354bf" },
  { name = "ttf", text = "", fg = "#ececec" },
  { name = "txt", text = "󰈙", fg = "#89e051" },
  { name = "txz", text = "", fg = "#eca517" },
  { name = "typ", text = "", fg = "#0dbcc0" },
  { name = "ui", text = "", fg = "#015bf0" },
  { name = "vim", text = "", fg = "#019833" },
  { name = "vue", text = "", fg = "#8dc149" },
  { name = "wasm", text = "", fg = "#5c4cdb" },
  { name = "wav", text = "", fg = "#00afff" },
  { name = "webm", text = "", fg = "#fd971f" },
  { name = "webp", text = "", fg = "#a074c4" },
  { name = "webpack", text = "󰜫", fg = "#519aba" },
  { name = "wma", text = "", fg = "#00afff" },
  { name = "wmv", text = "", fg = "#fd971f" },
  { name = "woff", text = "", fg = "#ececec" },
  { name = "woff2", text = "", fg = "#ececec" },
  { name = "wv", text = "", fg = "#00afff" },
  { name = "wvc", text = "", fg = "#00afff" },
  { name = "xcf", text = "", fg = "#635b46" },
  { name = "xcstrings", text = "", fg = "#2596be" },
  { name = "xls", text = "󰈛", fg = "#207245" },
  { name = "xlsx", text = "󰈛", fg = "#207245" },
  { name = "xml", text = "󰗀", fg = "#e37933" },
  { name = "xpi", text = "", fg = "#ff1b01" },
  { name = "xslt", text = "󰗀", fg = "#33a9dc" },
  { name = "xz", text = "", fg = "#eca517" },
  { name = "yaml", text = "", fg = "#6d8086" },
  { name = "yml", text = "", fg = "#6d8086" },
  { name = "zig", text = "", fg = "#f69a1b" },
  { name = "zip", text = "", fg = "#eca517" },
  { name = "zsh", text = "", fg = "#89e051" },
  { name = "zst", text = "", fg = "#eca517" },
]
