# htps://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[[language]]
name = "fish"
auto-format = true
formatter = { command = "fish_indent", args = ["-"] }

[[language]]
name = "ini"
file-types = ["conf"]

[[language]]
name = "kanata"
grammar = "kanata"
scope = "source.kanata"
file-types = ["kbd"]
comment-tokens = [";;"]

[[grammar]]
name = "kanata"
source = { git = "https://github.com/AminurAlam/tree-sitter-kanata", rev = "e8d56b0675824723aa283e84e441c6709b61b722" }

[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["-f", "$HOME/repos/dotfiles/other/stylua.toml", "-"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff"]

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "typst"
scope = "source.typst"
file-types = ["typst", "typ"]
indent = { tab-width = 2, unit = "  " }
comment-token = "//"
injection-regex = "typ(st|c)?"
auto-pairs = { '(' = ')', '{' = '}', '[' = ']', '$' = '$', '"' = '"', '`' = '`' }
