# htps://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[[language]]
name        = "lua"
auto-format = true
formatter   = { command = "stylua", args = ["-f", "$HOME/repos/dotfiles/other/stylua.toml", "-"] }

[[language]]
name             = "python"
auto-format      = true
language-servers = ["basedpyright", "ruff"]

[[language]]
name        = "fish"
auto-format = true
formatter   = { command = "fish_indent", args = ["-"] }

[[language]]
name        = "toml"
auto-format = true

[[language]]
name           = "kanata"
grammar        = "kanata"
scope          = "source.kanata"
file-types     = ["kbd"]
comment-tokens = [";;"]

[[grammar]]
name   = "kanata"
source = { git = "https://github.com/AminurAlam/tree-sitter-kanata", rev = "96ab54c669433c90e1cb5bca950afbd32ebe148f" }
# source = { git = "https://github.com/glehmann/tree-sitter-kanata", rev = "e3f368ded70efbaeba0273390b1bbfb6c4a94c22" }
